# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - billing-functionapp-simran

on:
  push:
    branches:
      - main
    paths:
      - 'BillingFunctions/**'
      - '.github/workflows/main_billing-functionapp-simran.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './BillingFunctions' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          cd BillingFunctions
              dotnet build --configuration Release
              dotnet publish -c Release -o output
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'billing-functionapp-simran'
          slot-name: 'Production'
          package: './BillingFunctions/output'        
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BD448A8EDDA04BF98BE3C3DDAD51E6FF }}
